<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>XYZCartoes</RootNamespace>
    <AssemblyName>XYZCartoes</AssemblyName>
    <StartupObject>XYZCartoes.Program</StartupObject>
    <MyType>Console</MyType>
    <OptionExplicit>On</OptionExplicit>
    <OptionStrict>On</OptionStrict>
    <OptionCompare>Binary</OptionCompare>
    <OptionInfer>On</OptionInfer>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.1" />
  </ItemGroup>

</Project>
